- name: package installation on hosts
  hosts: all
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: 
          - httpd
          - nginx
        state: present
   