- name: package installation on hosts
  hosts: all
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: httpd
        state: present

    - name: downloading template
      shell: wget https://www.free-css.com/assets/files/free-css-templates/download/page287/cycle.zip